// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc-iAFETNXxEcuOE8MFt8oP2Ps0QUHq6M',
    appId: '1:116582584509:web:6e4789aafb6752f94b67d4',
    messagingSenderId: '116582584509',
    projectId: 'krishportfoilio',
    authDomain: 'krishportfoilio.firebaseapp.com',
    storageBucket: 'krishportfoilio.firebasestorage.app',
    measurementId: 'G-GJCC61X22Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXwKppr1HvL_AA2GOeEiH5Je5wnYpj0d0',
    appId: '1:116582584509:android:e62482dc473351044b67d4',
    messagingSenderId: '116582584509',
    projectId: 'krishportfoilio',
    storageBucket: 'krishportfoilio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzak7nAatZqSVTSRMsiE4DbDP_QONu5Hw',
    appId: '1:116582584509:ios:1f7ca4230dcf5e6f4b67d4',
    messagingSenderId: '116582584509',
    projectId: 'krishportfoilio',
    storageBucket: 'krishportfoilio.firebasestorage.app',
    iosBundleId: 'com.high.app.awesomePortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzak7nAatZqSVTSRMsiE4DbDP_QONu5Hw',
    appId: '1:116582584509:ios:1f7ca4230dcf5e6f4b67d4',
    messagingSenderId: '116582584509',
    projectId: 'krishportfoilio',
    storageBucket: 'krishportfoilio.firebasestorage.app',
    iosBundleId: 'com.high.app.awesomePortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc-iAFETNXxEcuOE8MFt8oP2Ps0QUHq6M',
    appId: '1:116582584509:web:bf1ad8becd06ff904b67d4',
    messagingSenderId: '116582584509',
    projectId: 'krishportfoilio',
    authDomain: 'krishportfoilio.firebaseapp.com',
    storageBucket: 'krishportfoilio.firebasestorage.app',
    measurementId: 'G-70CT48CKZM',
  );
}
